version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: aprobaciones-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: aprobaciones_db
      TZ: America/Bogota
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: aprobaciones-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      TZ: America/Bogota
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aprobaciones-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - mongo
    environment:
      DATABASE_URL: postgresql://app_user:app_password@postgres:5432/aprobaciones_db?schema=public
      MONGO_URL: mongodb://admin:admin123@mongo:27017/aprobaciones_history?authSource=admin
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USER: TU_CORREO@gmail.com
      MAIL_PASS: TU_CONTRASEÃ‘A_DE_APLICACION
      MAIL_FROM: "Flujo de Aprobaciones <TU_CORREO@gmail.com>"
      TZ: America/Bogota
    networks:
      - app-network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node prisma/seed-runtime.cjs &&
        node dist/app.js
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aprobaciones-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://backend:4000
      TZ: America/Bogota
    networks:
      - app-network

volumes:
  postgres_data:
  mongo_data:

networks:
  app-network:
    driver: bridge
